name: Autoupdate
on:
  schedule:
    - cron: "40 11 * * *"
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Update react-pdf
        run: npm update @react-pdf/renderer
      - name: Update react-pdf
        run: npm update @react-pdf/renderer
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
